/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package de.uka.aifb.com.systemDynamics.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int TIMES = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int OPEN_PAR = 6;
  /** RegularExpression Id. */
  int CLOSE_PAR = 7;
  /** RegularExpression Id. */
  int AUXILIARY_NODE = 8;
  /** RegularExpression Id. */
  int CONSTANT_NODE = 9;
  /** RegularExpression Id. */
  int LEVEL_NODE = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int ROUND = 12;
  /** RegularExpression Id. */
  int function = 13;
  /** RegularExpression Id. */
  int MINIMUM = 14;
  /** RegularExpression Id. */
  int MAXIMUM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"AN\"",
    "\"CN\"",
    "\"LN\"",
    "<ID>",
    "\"RD\"",
    "\"f()\"",
    "\"MIN\"",
    "\"MAX\"",
  };

}
